import Head from "next/head";
import Banner from "../components/Banner";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import { useAPI } from "../components/useAPI";

const urbanSlugs = [
  {
    slug: "aarhus",
  },
  {
    slug: "andorra",
  },
  {
    slug: "florence",
  },
  {
    slug: "frankfurt",
  },
];

const DEFAULT_IMAGE =
  "https://images.unsplash.com/photo-1659787050050-d5aa2b1ec0dc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=818&q=80";

export default function Home({ exploreData }) {
  const { results } = exploreData;
  const { data: firstCardData, imageData: firstCardImage } = useAPI(
    urbanSlugs[0].slug
  );
  const { data: secondCardData, imageData: secondCardImage } = useAPI(
    urbanSlugs[1].slug
  );
  const { data: thirdCardData, imageData: thirdCardImage } = useAPI(
    urbanSlugs[2].slug
  );
  const { data: fourthCardData, imageData: fourthCardImage } = useAPI(
    urbanSlugs[3].slug
  );

  return (
    <>
      <Head>
        <title>AirBnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-10">
          <h2 className="text-4xl font-semibold pb-5">
            Explore Renters Nearby
          </h2>

          {/* cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {results?.map((item, i) => (
              <SmallCard key={i} item={item} />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            <MediumCard
              data={firstCardData ? firstCardData : null}
              img={firstCardImage ? firstCardImage : DEFAULT_IMAGE}
            />
            <MediumCard
              data={secondCardData ? secondCardData : null}
              img={secondCardImage ? secondCardImage : DEFAULT_IMAGE}
            />
            <MediumCard
              data={thirdCardData ? thirdCardData : null}
              img={thirdCardImage ? thirdCardImage : DEFAULT_IMAGE}
            />
            <MediumCard
              data={fourthCardData ? fourthCardData : null}
              img={fourthCardImage ? fourthCardImage : DEFAULT_IMAGE}
            />
          </div>
        </section>

        <LargeCard
          img={"https://links.papareact.com/4cj"}
          title="The Greatest Outdoors"
          desc={"Wishlist created by Airbnb."}
          buttText="Get Inspired"
        />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://randomuser.me/api/?results=9").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
    },
  };
}
